# Generated by Django 3.0.1 on 2020-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_review_author'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(to='articles.Movie'),
        ),
    ]
