# Generated by Django 3.0.1 on 2020-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_review_author'),
        ('users', '0003_auto_20200603_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='follows',
        ),
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to='articles.Movie'),
        ),
    ]
