# Generated by Django 3.0.1 on 2020-06-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_review_author'),
        ('users', '0004_auto_20200603_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follower', to='articles.Movie'),
        ),
    ]
