# Generated by Django 3.0.1 on 2020-06-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200604_1129'),
        ('users', '0005_auto_20200603_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='downvotes_discussion',
            field=models.ManyToManyField(blank=True, related_name='discussion_downvoter', to='articles.Discussion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upvotes_discussion',
            field=models.ManyToManyField(blank=True, related_name='discussion_upvoter', to='articles.Discussion'),
        ),
    ]
