# Generated by Django 3.0.1 on 2020-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
