# Generated by Django 3.0.6 on 2020-05-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
