# Generated by Django 3.0.1 on 2020-06-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200604_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='downvoters',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='upvoters',
        ),
    ]
