# Generated by Django 3.0.1 on 2020-06-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200604_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='downvoters_counter',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='upvoters_counter',
        ),
    ]
