# Generated by Django 3.0.1 on 2020-06-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200606_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='articles.Movie'),
        ),
    ]
