# Generated by Django 3.0.1 on 2020-06-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200607_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
