# Generated by Django 3.0.1 on 2020-06-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='contentRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imDbRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='releaseDate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtimeStr',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
    ]
