# Generated by Django 3.0.1 on 2020-07-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200607_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imDbid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
