# Generated by Django 3.0.1 on 2020-07-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_movie_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='website_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
