# Generated by Django 3.0.1 on 2020-07-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_movie_website_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='website_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
