# Generated by Django 3.0.1 on 2020-07-04 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threadedcomments', '0003_threadedcomment_newest_activity'),
        ('report', '0002_auto_20200614_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_report', to='threadedcomments.ThreadedComment'),
        ),
    ]
